### PR TITLE
Update README.md to include ignore tips

### PR DESCRIPTION
**Pull request by RolfMoleman**
Fixes #

## Proposed Changes

1. Add table of contents to readme
2. Add navigation links back to TOC
3. Update Megalinter URLs
4. Add information on ignoring code and why you might want to

### Author/Contributor
- [x] Add entry to the **CHANGELOG.md** listing the change and linking to the corresponding issue (if appropriate)
- [x] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by nvuillam** [comment]
@RolfMoleman i'm trying to solve the CI jobs issues in your branch , because MegaLinter had not been upgraded for some time ^^

**Comment by nvuillam** [comment]
You can remove the 


[(Back to the Table of Contents)](#table-of-contents)

the README is not big enough to need that ^^

**Comment by RolfMoleman** [comment]
@nvuillam apologies for the delay, made the changes on my phone.

I’ve added a record to the changelog treating my amendments as a patch. Is that sufficient??

**Comment by nvuillam** [comment]
Ci job will say :)
We're not such in a hurry, you can wait to be on a computer 😁

**Review by nvuillam — APPROVED** [review]
Thanks for your contribution :) :)

**Comment by RolfMoleman** [comment]
@nvuillam i've marked issue #15 as closed as well.

Thank you too.

**Comment by nvuillam** [comment]
Happy formatting 🥳

**Pull request merged**
